# Generated by Django 3.2.24 on 2024-03-01 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=503, verbose_name='اسم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگها',
            },
        ),
        migrations.AddField(
            model_name='proguide',
            name='tags',
            field=models.ManyToManyField(to='core.Tag', verbose_name='تگ'),
        ),
    ]
