# Generated by Django 3.2.25 on 2024-03-08 06:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240304_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='proguide',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.proguide_image_file_path, verbose_name='تصویر'),
        ),
    ]
