---
name: Checks
# name .. going to appear in github action

on : [push]
# this is trigger // run on push = any push of changes to our project

jobs : 
  test-lint:
    name: Test and Lint
    runs-on : ubuntu-20.04
  # new job with test-lint id / set the name and operating system
    steps:
      - name: Login to Docker Hub
    # this step just will be login to dockerhub
        uses: docker/login-action@v1
        # it allows to use a predefined action in GitHub
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
    # this step will be check our code inside github action job
      - name: Test
        run : docker-compose run --rm app sh -c "python manage.py wait_for_db &&
                                                 python manage.py test"
    # this step just do(run) the unit test
      - name: Lint
        run : docker-compose run --rm app sh -c "flake8"
    # this step run the linting / 
